name: Defect Report
description: Log a defect using the QA defect format
labels: ["bug"]
body:
  - type: input
    id: defect-id
    attributes:
      label: Defect ID
      description: Optional internal reference (e.g. BUG-008)
      placeholder: 'BUG-###'
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief summary of the defect
      placeholder: Provide a clear, concise description of the issue
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current defect status
      options:
        - New
        - Working on
        - Verified
        - Done
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact level of the defect
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Priority level for fixing this defect
      options:
        - P1
        - P2
        - P3
        - P4
        - P5
    validations:
      required: true
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Any setup required before reproducing the issue
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Clear step-by-step instructions
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happens
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions
      description: 'Optional suggestions, observations, or possible fixes'
      placeholder: 'Any ideas, edge cases, or related notes'
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: 'OS, browser, app version, etc.'
      placeholder: Mac OS / Browser / App version
    validations:
      required: false
